//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSClient.DoctorServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DoctorServiceRef.IDoctorService")]
    public interface IDoctorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/GetDoctorsByDeptId", ReplyAction="http://tempuri.org/IDoctorService/GetDoctorsByDeptIdResponse")]
        string[] GetDoctorsByDeptId(int deptId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/GetDoctorsByDeptId", ReplyAction="http://tempuri.org/IDoctorService/GetDoctorsByDeptIdResponse")]
        System.Threading.Tasks.Task<string[]> GetDoctorsByDeptIdAsync(int deptId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/GetDoctorIdByName", ReplyAction="http://tempuri.org/IDoctorService/GetDoctorIdByNameResponse")]
        int GetDoctorIdByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/GetDoctorIdByName", ReplyAction="http://tempuri.org/IDoctorService/GetDoctorIdByNameResponse")]
        System.Threading.Tasks.Task<int> GetDoctorIdByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/GetDoctorIdByUserName", ReplyAction="http://tempuri.org/IDoctorService/GetDoctorIdByUserNameResponse")]
        int GetDoctorIdByUserName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoctorService/GetDoctorIdByUserName", ReplyAction="http://tempuri.org/IDoctorService/GetDoctorIdByUserNameResponse")]
        System.Threading.Tasks.Task<int> GetDoctorIdByUserNameAsync(string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDoctorServiceChannel : HMSClient.DoctorServiceRef.IDoctorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoctorServiceClient : System.ServiceModel.ClientBase<HMSClient.DoctorServiceRef.IDoctorService>, HMSClient.DoctorServiceRef.IDoctorService {
        
        public DoctorServiceClient() {
        }
        
        public DoctorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoctorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoctorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoctorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetDoctorsByDeptId(int deptId) {
            return base.Channel.GetDoctorsByDeptId(deptId);
        }
        
        public System.Threading.Tasks.Task<string[]> GetDoctorsByDeptIdAsync(int deptId) {
            return base.Channel.GetDoctorsByDeptIdAsync(deptId);
        }
        
        public int GetDoctorIdByName(string name) {
            return base.Channel.GetDoctorIdByName(name);
        }
        
        public System.Threading.Tasks.Task<int> GetDoctorIdByNameAsync(string name) {
            return base.Channel.GetDoctorIdByNameAsync(name);
        }
        
        public int GetDoctorIdByUserName(string userName) {
            return base.Channel.GetDoctorIdByUserName(userName);
        }
        
        public System.Threading.Tasks.Task<int> GetDoctorIdByUserNameAsync(string userName) {
            return base.Channel.GetDoctorIdByUserNameAsync(userName);
        }
    }
}
